WHITESPACE =_{" " | "\t" }

command_line = _{command_single_line ~ (pipe ~ command_single_line)* }

pipe = _{WHITESPACE* ~ "|" ~ WHITESPACE*}

command_single_line = _{command ~ options* ~ arguments* ~ !(options | todo_parse) }

command = @{!WHITESPACE ~ ASCII_ALPHA_LOWER+ ~ !options}

options = @{("--" | "-") ~ ASCII_ALPHA_LOWER+ }

arguments = @{!WHITESPACE ~ ASCII_ALPHA_LOWER+ ~ !options}

todo_parse = _{"&&" | "||" | ">" | "<"}
