WHITESPACE = _{ " " | "\t" }

command_line = _{ command_with_flags_and_args ~ (pipe ~ command_with_flags_and_args)* }

pipe = _{ WHITESPACE* ~ "|" ~ WHITESPACE* }

command_with_flags_and_args = @{ command ~ (WHITESPACE+ ~ (options | arguments))* }

command = @{ ASCII_ALPHA_LOWER+ }  // El nombre del comando (ej: "ls", "grep")

options = @{ ("--" | "-") ~ ASCII_ALPHA_LOWER+ }  // Opciones (ej: "-l", "--ignore-case")

arguments = @{ ASCII_ALPHANUMERIC+ }  // Argumentos (ej: "file.txt")

